runtime: python27
threadsafe: true

handlers:
- url: /foto
  static_dir: foto

- url: /
  static_files: index.html
  upload: index.html

- url: /style.css
  static_files: style.css
  upload: style.css
